In [ ]:
import numpy as np

def calculate_Lw_individual(Lw_ref, a, b, c, d, zeta, RPM, C_proc, num_rotors):
    """
    Calculate the sound power level for an individual rotor with power split adjustment.
    
    Parameters:
    - Lw_ref (array-like): Reference sound power level for different frequencies.
    - a, b, c, d (array-like): Coefficients for the polynomial model.
    - zeta (float): Radiation angle in degrees.
    - RPM (float): Rotational speed of the rotor.
    - C_proc (float): Procedural correction factor.
    - num_rotors (int): Total number of rotors.

    Returns:
    - Lw_individual (array-like): Adjusted sound power levels for the rotor.
    """
    # Calculate the individual rotor sound power level
    Lw_individual = (
        Lw_ref 
        + a * (zeta ** 2) 
        + b * np.abs(zeta) 
        + c * RPM 
        + d * (RPM ** 2) 
        + C_proc
        - 10 * np.log10(num_rotors)  # Adjust for power split
    )
    return Lw_individual

def calculate_Lw_total(Lw_individual_list):
    """
    Calculate the total sound power level by combining individual rotor contributions energetically.
    
    Parameters:
    - Lw_individual_list (list of array-like): List of adjusted sound power levels for all rotors.

    Returns:
    - Lw_total (array-like): Total sound power levels across all frequencies.
    """
    # Combine the individual sound power levels energetically
    Lw_total = 10 * np.log10(np.sum([10 ** (Lw / 10) for Lw in Lw_individual_list], axis=0))
    return Lw_total

# Example Usage:
# Define example inputs
num_rotors = 4
RPMs = [5000, 5500, 6000, 5500]  # Rotational speeds of the 4 rotors
zeta = 30  # Radiation angle in degrees
C_proc = 2.0  # Procedural correction factor
Lw_ref = np.array([80, 75, 70])  # Reference levels for 3 example frequencies
a = np.array([0.1, 0.2, 0.15])  # Coefficients for zeta^2
b = np.array([0.05, 0.1, 0.08])  # Coefficients for |zeta|
c = np.array([0.01, 0.02, 0.015])  # Coefficients for RPM
d = np.array([1e-6, 2e-6, 1.5e-6])  # Coefficients for RPM^2

# Calculate individual sound power levels
Lw_individual_list = [
    calculate_Lw_individual(Lw_ref, a, b, c, d, zeta, RPM, C_proc, num_rotors) for RPM in RPMs
]

# Calculate total sound power level
Lw_total = calculate_Lw_total(Lw_individual_list)

Lw_individual_list, Lw_total


([array([242.47940009, 403.97940009, 315.87940009]),
  array([252.72940009, 424.47940009, 331.25440009]),
  array([263.47940009, 445.97940009, 347.37940009]),
  array([252.72940009, 424.47940009, 331.25440009])],
 array([264.18429422, 446.0407304 , 347.58930863]))

: 